### ISSUE TITLE
Ghidra 9.1 Support

### ISSUE THREAD

**Issue by Ristovski** [leveldown-security/SVD-Loader-Ghidra#2]
Under 9.1 BETA, running the loader fails with
```
    from ghidra.app.cmd.memory import AddMemoryBlockCmd
ImportError: cannot import name AddMemoryBlockCmd
```

this is due to `AddMemoryBlockCmd` no longer being available.
See https://github.com/NationalSecurityAgency/ghidra/commit/079241797945cc2965886a2cbce7be449e7bda2c#diff-d846121bca9672c57ac899aa6a544325

**Comment by brainstorm** [comment]
@Ristovski Did you see a similar method on 9.1 that might do the same? I just hit this issue and would like to know if you already fixed it, otherwise I can take a look.

**Comment by brainstorm** [comment]
Meh, that was an easy fix, just change it for `AddInitializedMemoryBlockCmd` and you'll be fine ;)

Might do a PR later...

**Comment by nezza** [comment]
Should be fixed - that import was unused anyway :)
